theme: jekyll-theme-minimal
title: Adeel Ahmad
description: Laboratoire d’Informatique Signal et Image de la Cˆote d’Opale (LISIC) - UR 4491, Universit´e du Littoral Cˆote d’Opale (ULCO)
url: https://dr-adeel.github.io
author: Adeel Ahmad, Maître de Conférences en Informatique, Directeur des études et Président de Jury Licence 2 Informatique
avatar: "images/profile-up.jpg"
